version: '3'
services:
  app:
    #linhas comentadas porque buildei a imagem
    build:
      context: .
      dockerfile: Dockerfile
    #image: apache-estoque:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db-estoque
    links:
      - db-estoque

  db-estoque:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=env('DB_ROOT_PASSWORD')
      - MYSQL_DATABASE=env('DB_DATABASE')
      - MYSQL_USER=env('DB_USERNAME')
      - MYSQL_PASSWORD=env('DB_PASSWORD')
    volumes:
      - /home/concer/containers/indicadores/estoque/stg_db:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --log-bin-trust-function-creators=1
